version: '3.9'

services:
  traefik:
    image: traefik:v2.11
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      # LetsEncrypt SSL
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=your-email@example.com' # Define your email here
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      # Self-Signed Certificate
      # - "--entrypoints.websecure.http.tls.certificates.certfile=/path/to/cert.pem"
      # - "--entrypoints.websecure.http.tls.certificates.keyfile=/path/to/key.pem"
    ports:
      - '80:80' # The HTTP port
      - '443:443' # The HTTPS port
      - '8080:8080' # The Traefik Dashboard port
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      # LetsEncrypt SSL
      - './letsencrypt:/letsencrypt'
      # Self-Signed Certificate
      # - "./path/to/cert.pem:/path/to/cert.pem"
      # - "./path/to/key.pem:/path/to/key.pem"

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.example.com`)' # Define the hostname to be able to view the trafik dashboard
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/' # Username & Password
  backend:
    container_name: Backend
    build: .
    command: >
      sh -c "
      if [ '$$ENVIRONMENT' = 'dev' ] ; then
        uvicorn app.main:app --reload --host 0.0.0.0 --port $$FASTAPI_PORT;
      else
        uvicorn app.main:app --host 0.0.0.0 --port $$FASTAPI_PORT;
      fi"
    ports:
      - 127.0.0.1:${FASTAPI_PORT}:${FASTAPI_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'
    labels:
      - 'traefik.enable=false'

  frontend:
    container_name: Frontend
    stdin_open: true
    build:
      context: ./frontend
      args:
        HOST: ${HOST}
        FASTAPI_PORT: ${FASTAPI_PORT}
    env_file:
      - .env
    expose:
      - 8000
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`your-frontend-domain.com`)' # frontend url
      - 'traefik.http.routers.frontend.entrypoints=web'
      - 'traefik.http.routers.frontend-secured.rule=Host(`your-frontend-domain.com`)' # frontend url
      - 'traefik.http.routers.frontend-secured.entrypoints=websecure'
      - 'traefik.http.routers.frontend-secured.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.frontend.middlewares=redirect-to-https'
